### ISSUE TITLE
Module prevents required asterisk appearing in field headers

### ISSUE THREAD

**Issue by Toutouwai** [teppokoivula/VersionControl#28]
Copying this over from a [forum comment](https://processwire.com/talk/topic/6333-version-control/?do=findComment&comment=164746) that might have been overlooked.

The Version Control module is preventing the red asterisk from appearing in the header of required fields. The relevant admin CSS is:

```css
.InputfieldStateRequired>.InputfieldHeader:first-child:after {
    content: ' *';
    color: #C00C19;
}
```

The addition of the field-revisions div interferes with this.

P.S. This relates to the dev branch - not sure if the v1 branch is also affected.

**Comment by Toutouwai** [comment]
I'm not actually sure why this admin CSS needs the `:first-child` part. As far as I know there is only ever one `.InputfieldHeader` element as a direct child of an `.InputfieldStateRequired` element, so maybe it would be worth asking Ryan if the CSS could simply be:

```css
.InputfieldStateRequired>.InputfieldHeader:after {
    content: ' *';
    color: #C00C19;
}
```
