### ISSUE TITLE
Scroll bars on revisions div (dev branch)

### ISSUE THREAD

**Issue by Toutouwai** [teppokoivula/VersionControl#30]
There are unnecessary scroll bars on the revisions div:

![2020-01-29_142329](https://user-images.githubusercontent.com/1538852/73320014-faea0f80-42a2-11ea-939f-0d12d1be9085.png)

Possible fix: change...

```css
.field-revisions > div {
    overflow: scroll !important;
}
```

...to...

```css
.field-revisions > div {
    overflow: auto !important;
}
```
